//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHotel.Clients.Core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SmartHotel.Clients.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MisParcelas {
            get {
                return ResourceManager.GetString("MisParcelas", resourceCulture);
            }
        }
        
        internal static string MisTratamientos {
            get {
                return ResourceManager.GetString("MisTratamientos", resourceCulture);
            }
        }
        
        internal static string MisTratamientosSub {
            get {
                return ResourceManager.GetString("MisTratamientosSub", resourceCulture);
            }
        }
        
        internal static string AccesoDirecto1 {
            get {
                return ResourceManager.GetString("AccesoDirecto1", resourceCulture);
            }
        }
        
        internal static string AccesoDirecto2 {
            get {
                return ResourceManager.GetString("AccesoDirecto2", resourceCulture);
            }
        }
        
        internal static string SeleccioneLista {
            get {
                return ResourceManager.GetString("SeleccioneLista", resourceCulture);
            }
        }
        
        internal static string ActivateEcoMode {
            get {
                return ResourceManager.GetString("ActivateEcoMode", resourceCulture);
            }
        }
        
        internal static string AmbientLight {
            get {
                return ResourceManager.GetString("AmbientLight", resourceCulture);
            }
        }
        
        internal static string AmbientSettings {
            get {
                return ResourceManager.GetString("AmbientSettings", resourceCulture);
            }
        }
        
        internal static string BeGreen {
            get {
                return ResourceManager.GetString("BeGreen", resourceCulture);
            }
        }
        
        internal static string BookMayus {
            get {
                return ResourceManager.GetString("BookMayus", resourceCulture);
            }
        }
        
        internal static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        internal static string ConferenceRoom {
            get {
                return ResourceManager.GetString("ConferenceRoom", resourceCulture);
            }
        }
        
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        internal static string CurrentJson {
            get {
                return ResourceManager.GetString("CurrentJson", resourceCulture);
            }
        }
        
        internal static string DialogBookingMessage {
            get {
                return ResourceManager.GetString("DialogBookingMessage", resourceCulture);
            }
        }
        
        internal static string DialogBookingTitle {
            get {
                return ResourceManager.GetString("DialogBookingTitle", resourceCulture);
            }
        }
        
        internal static string DialogNo {
            get {
                return ResourceManager.GetString("DialogNo", resourceCulture);
            }
        }
        
        internal static string DialogOk {
            get {
                return ResourceManager.GetString("DialogOk", resourceCulture);
            }
        }
        
        internal static string DialogYes {
            get {
                return ResourceManager.GetString("DialogYes", resourceCulture);
            }
        }
        
        internal static string DoubleRoom {
            get {
                return ResourceManager.GetString("DoubleRoom", resourceCulture);
            }
        }
        
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        internal static string ExceptionTitle {
            get {
                return ResourceManager.GetString("ExceptionTitle", resourceCulture);
            }
        }
        
        internal static string FindRoom {
            get {
                return ResourceManager.GetString("FindRoom", resourceCulture);
            }
        }
        
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        internal static string HttpRequestExceptionMessage {
            get {
                return ResourceManager.GetString("HttpRequestExceptionMessage", resourceCulture);
            }
        }
        
        internal static string HttpRequestExceptionTitle {
            get {
                return ResourceManager.GetString("HttpRequestExceptionTitle", resourceCulture);
            }
        }
        
        internal static string IndividualRoom {
            get {
                return ResourceManager.GetString("IndividualRoom", resourceCulture);
            }
        }
        
        internal static string LoadJson {
            get {
                return ResourceManager.GetString("LoadJson", resourceCulture);
            }
        }
        
        internal static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        internal static string NewBookingMayus {
            get {
                return ResourceManager.GetString("NewBookingMayus", resourceCulture);
            }
        }
        
        internal static string NextMayus {
            get {
                return ResourceManager.GetString("NextMayus", resourceCulture);
            }
        }
        
        internal static string NfcMessage01 {
            get {
                return ResourceManager.GetString("NfcMessage01", resourceCulture);
            }
        }
        
        internal static string NfcMessage02 {
            get {
                return ResourceManager.GetString("NfcMessage02", resourceCulture);
            }
        }
        
        internal static string OpenDoor {
            get {
                return ResourceManager.GetString("OpenDoor", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string RemoteJson {
            get {
                return ResourceManager.GetString("RemoteJson", resourceCulture);
            }
        }
        
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        internal static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        internal static string RoomTemperature {
            get {
                return ResourceManager.GetString("RoomTemperature", resourceCulture);
            }
        }
        
        internal static string SeeYou {
            get {
                return ResourceManager.GetString("SeeYou", resourceCulture);
            }
        }
        
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string SignInMayus {
            get {
                return ResourceManager.GetString("SignInMayus", resourceCulture);
            }
        }
        
        internal static string SignInGuest {
            get {
                return ResourceManager.GetString("SignInGuest", resourceCulture);
            }
        }
        
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        internal static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        internal static string TheHotel {
            get {
                return ResourceManager.GetString("TheHotel", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        internal static string WindowBlinds {
            get {
                return ResourceManager.GetString("WindowBlinds", resourceCulture);
            }
        }
        
        internal static string CheckInOut {
            get {
                return ResourceManager.GetString("CheckInOut", resourceCulture);
            }
        }
        
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        internal static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        internal static string EatToday {
            get {
                return ResourceManager.GetString("EatToday", resourceCulture);
            }
        }
        
        internal static string BookConferenceMayus {
            get {
                return ResourceManager.GetString("BookConferenceMayus", resourceCulture);
            }
        }
        
        internal static string GoMyRoomMayus {
            get {
                return ResourceManager.GetString("GoMyRoomMayus", resourceCulture);
            }
        }
        
        internal static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        internal static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        internal static string DoToday {
            get {
                return ResourceManager.GetString("DoToday", resourceCulture);
            }
        }
        
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        internal static string Coming {
            get {
                return ResourceManager.GetString("Coming", resourceCulture);
            }
        }
        
        internal static string HighOccupancy {
            get {
                return ResourceManager.GetString("HighOccupancy", resourceCulture);
            }
        }
        
        internal static string LowOccupancy {
            get {
                return ResourceManager.GetString("LowOccupancy", resourceCulture);
            }
        }
        
        internal static string MediumOccupancy {
            get {
                return ResourceManager.GetString("MediumOccupancy", resourceCulture);
            }
        }
        
        internal static string NoNfc {
            get {
                return ResourceManager.GetString("NoNfc", resourceCulture);
            }
        }
        
        internal static string ExceptionB2CMessage {
            get {
                return ResourceManager.GetString("ExceptionB2CMessage", resourceCulture);
            }
        }
        
        internal static string BotError {
            get {
                return ResourceManager.GetString("BotError", resourceCulture);
            }
        }
        
        internal static string BotSelectionMessage {
            get {
                return ResourceManager.GetString("BotSelectionMessage", resourceCulture);
            }
        }
        
        internal static string BotSelectionTitle {
            get {
                return ResourceManager.GetString("BotSelectionTitle", resourceCulture);
            }
        }
        
        internal static string DeactivateEcoMode {
            get {
                return ResourceManager.GetString("DeactivateEcoMode", resourceCulture);
            }
        }
        
        internal static string IoTError_DataType {
            get {
                return ResourceManager.GetString("IoTError_DataType", resourceCulture);
            }
        }
    }
}
